name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run unit test
        run: yarn test
