name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run test
        run: yarn test
